# Generated by Django 2.1.7 on 2019-05-11 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Clocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('passwordSalt', models.CharField(max_length=50)),
                ('passwordHashAlgorithm', models.CharField(max_length=50)),
                ('passwordReminderToken', models.CharField(max_length=100)),
                ('passwordReminderExpiration', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Incidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='IncidenceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoursDeducted', models.PositiveSmallIntegerField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateTimeField()),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateTimeField()),
                ('completed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('weekday', models.PositiveSmallIntegerField()),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Employee')),
                ('workID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Work')),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='workTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.WorkType'),
        ),
        migrations.AddField(
            model_name='incidence',
            name='incidenceTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.IncidenceType'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employeeAccountID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.EmployeeAccount'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='employeeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Employee'),
        ),
    ]
