# Generated by Django 2.2.1 on 2019-06-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
