# Generated by Django 2.2.1 on 2019-06-16 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='hours_deducted',
        ),
        migrations.AlterField(
            model_name='payroll',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='HoursDeducted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_deducted', models.PositiveSmallIntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Employee')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Payroll')),
            ],
        ),
    ]
