# Generated by Django 2.1.7 on 2019-05-18 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190517_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='employeeID',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='lastname',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='incidence',
            old_name='employeeID',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='incidence',
            old_name='incidenceTypeID',
            new_name='incidence_type',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='employeeID',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='hoursDeducted',
            new_name='hours_deducted',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='workTypeID',
            new_name='work_type',
        ),
        migrations.RenameField(
            model_name='workschedule',
            old_name='employeeID',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='workschedule',
            old_name='endTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='workschedule',
            old_name='startTime',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='workschedule',
            old_name='workID',
            new_name='work',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employeeAccountID',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.DeleteModel(
            name='EmployeeAccount',
        ),
    ]
