# Generated by Django 2.2.1 on 2019-06-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190615_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='end_date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='start_date',
            field=models.DateField(unique=True),
        ),
    ]
